### PR TITLE
make IE compatible

### PR DESCRIPTION
**Pull request by yepzy**
cf issue #23

### CODE REVIEW

**Comment by hivokas** [comment]
Do we really need `arguments.length > 1`?

**Comment by hivokas** [comment]
I've removed the length check and minified the code.

`return 'window["'.$this->getJsHelperName().'"]=function(e){var n=void 0!==arguments[1]?arguments[1]:null;return[window.sharedDataNamespace].concat("string"==typeof e?e.split("."):[]).reduce(function(e,t){return e===n||"object"!=typeof e||void 0===e[t]?n:e[t]},window)}';`

Is that okay?

**Comment by yepzy** [comment]
@hivokas 

Yes it ok for me

**Comment by yepzy** [comment]
Hi @hivokas 

any update about this PR ?

**Comment by hivokas** [comment]
Sorry for the delay. I was very busy.

**Pull request merged**
